version: "2"

services:
    postgres:
        image: postgres:12.3
        ports:
            - "5678:5678"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=contacts
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql