version: "2"

services:
    mysql:
        image: mysql:8.0.32
        ports:
            - "3305:3305"
        environment:
            - MYSQL_ROOT_USER=mysql
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_DB=contacts
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
